name: Execution Performance

on:
  workflow_dispatch:
    inputs:
      testSuite:
        type: string
        description: 'testSuite'
        required: true
        default: 'restfulapidev.RestfulAPIDev'
      concurrent:
        type: string
        description: 'Quantity of users'
        required: true
        default: '10'
      duration:
        type: string
        description: 'Duration of seconds'
        required: true
        default: '10'

jobs:
  execrestfulapi:
    runs-on: ubuntu-latest
    name: Execution Performance Restful API Dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Execute test
        run: gradle gatlingRun --simulation=${{ inputs.testSuite }} -DconcurrentUsers=${{ inputs.concurrent }} -DdurationOfSeconds=${{ inputs.duration }}

      - name: Save report
        if: ${{always()}}
        uses: actions/upload-artifact@v3.1.2
        with:
          name: gatling report
          path: ./build/reports/gatling
      - name: "Publish test results"
        uses: peaceiris/actions-gh-pages@v3.7.3
        if: ${{ always() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './build/reports/gatling'
          keep_files: true
          user_name: yomarajazmin
          user_email: yomarajazmin@gmail.com
          publish_branch: gh_page
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./build/reports/gatling